
name: PR Tracker

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  pr-summary:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Use Node.js version 20.x
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      # Step 2: Checkout repository
      - name: Checkout FSOC.V2
        uses: actions/checkout@v2

      # Step 3: Fetch PRs using GitHub API
      - name: Fetch PRs
        run: |
          # Fetch the PRs and store the output in pr-summary.json
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://github.com/FSOC-OSS/FSOC.V2/pulls?state=all" \
          | tee pr-response.json # Save API response to a file

      # Step 4: Debugging - Check response format
      - name: Check API Response
        run: |
          cat pr-response.json # Output the raw API response to check the structure

      # Step 5: Process the PRs
      - name: Process PRs
        run: |
          jq '.[] | {title: .title, state: .state, merged: .merged_at, created_at: .created_at, user: .user.login}' pr-response.json > pr-summary.json
